### ISSUE TITLE
Newest version has error in is_hexarray

### ISSUE THREAD

**Issue by TheElementalOfDestruction** [seamustuohy/RTFDE#37]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python39\lib\site-packages\RTFDE\deencapsulate.py", line 118, in deencapsulate
    Decoder.update_children(self.full_tree)
  File "C:\Program Files\Python39\lib\site-packages\RTFDE\text_extraction.py", line 675, in update_children
    obj.children = [i for i in self.iterate_on_children(children)]
  File "C:\Program Files\Python39\lib\site-packages\RTFDE\text_extraction.py", line 675, in <listcomp>
    obj.children = [i for i in self.iterate_on_children(children)]
  File "C:\Program Files\Python39\lib\site-packages\RTFDE\text_extraction.py", line 725, in iterate_on_children
    elif is_hexarray(item):
  File "C:\Program Files\Python39\lib\site-packages\RTFDE\text_extraction.py", line 603, in is_hexarray
    if item.data.value == 'hexarray':
AttributeError: 'str' object has no attribute 'value'
```
Above is the traceback being returned, and I've attached a file that returns the error.

[failure.zip](https://github.com/user-attachments/files/17562207/failure.zip)

**Comment by TheElementalOfDestruction** [comment]
After further checking, I suspect something is likely wrong on my system. I'll try to verify this on a different system and report back.

**Comment by TheElementalOfDestruction** [comment]
Closing as this is confirmed to be a local issue. For whatever reason, pip was refusing to upgrade my version of lark which was highly outdated
